questions120 = {
  "1": "I often go out of my way to help others in need.",
  "2": "My own needs and goals are more important than helping others.",
  "3": "I enjoy making a positive difference in others' lives.",
  "4": "People should fend for themselves; I have my problems to deal with.",
  "5": "I find it easy to work cooperatively with others.",
  "6": "I prefer working independently rather than in a group.",
  "7": "Teamwork is essential for achieving common goals.",
  "8": "I often compete with my colleagues for recognition.",
  "9": "I downplay my achievements when talking with others.",
  "10": "I am comfortable highlighting my accomplishments.",
  "11": "I acknowledge the contributions of others before my own.",
  "12": "I tend to boast about my achievements.",
  "13": "I consider ethical principles in all my decisions.",
  "14": "In certain situations, bending the rules is acceptable.",
  "15": "I try to be fair and just in my interactions with others.",
  "16": "Sometimes, the end justifies the means.",
  "17": "I often feel deep sympathy for those who are less fortunate.",
  "18": "I am generally concerned about the well-being of others.",
  "19": "It's challenging for me to empathize with people in difficult situations.",
  "20": "I find it difficult to understand the feelings of others.",
  "21": "I generally trust others to act with good intentions.",
  "22": "I am cautious about trusting others too quickly.",
  "23": "I believe that most people are inherently good.",
  "24": "It takes time for me to feel comfortable opening up to others.",
  "25": "I set ambitious goals for myself.",
  "26": "I work hard to achieve my goals.",
  "27": "I strive for success in everything I do.",
  "28": "I am motivated to accomplish my tasks.",
  "29": "I often dive into tasks without thoroughly considering risks.",
  "30": "I prefer spontaneity over careful planning in my activities.",
  "31": "I rarely take the time to double-check my work for mistakes.",
  "32": "I find it unnecessary to establish clear and specific goals.",
  "33": "I am confident in my ability to handle unexpected events.",
  "34": "I believe I can effectively overcome challenges at work.",
  "35": "When faced with a difficult task, I am certain I can accomplish it.",
  "36": "I often doubt my ability to perform well in demanding situations.",
  "37": "I feel a strong sense of duty to others.",
  "38": "Fulfilling my responsibilities is essential to me.",
  "39": "Meeting deadlines is important to me.",
  "40": "Keeping my promises is important to me.",
  "41": "I often forget to put things back in their proper place.",
  "42": "I follow a schedule and dislike sudden changes.",
  "43": "I prefer a structured and organized lifestyle.",
  "44": "I resist changes to my established routine.",
  "45": "I am easily distracted and find it hard to stay focused on a task.",
  "46": "I tend to procrastinate and leave tasks unfinished.",
  "47": "I find it challenging to stick to a routine.",
  "48": "I struggle to control my impulses.",
  "49": "I often take part in activities that others find exciting and challenging.",
  "50": "I prefer spending time alone rather than socializing.",
  "51": "I enjoy being the center of attention in social gatherings.",
  "52": "I tend to have a low energy level and move slowly.",
  "53": "I am comfortable taking charge of situations and making decisions.",
  "54": "I avoid leadership roles and prefer to follow others' guidance.",
  "55": "I express my opinions and ideas confidently.",
  "56": "I often let others make decisions without asserting my preferences.",
  "57": "I often find myself feeling cheerful and optimistic.",
  "58": "It is rare for me to experience a sense of joy or elation.",
  "59": "I enjoy spreading positive energy and uplifting others.",
  "60": "I generally feel low-spirited and melancholic.",
  "61": "I actively seek out thrilling and adventurous experiences.",
  "62": "I prefer a calm and predictable life over one with frequent changes.",
  "63": "I often feel the need for excitement and stimulation.",
  "64": "I am cautious and avoid taking risks.",
  "65": "I am generally warm and friendly toward others.",
  "66": "I don't mind being alone, but I usually prefer to be with others.",
  "67": "I find it easy to approach others and start conversations.",
  "68": "I tend to be reserved and distant in social situations.",
  "69": "I enjoy being in large social gatherings with many people.",
  "70": "I prefer one-on-one conversations rather than group settings.",
  "71": "I feel energized when interacting with others.",
  "72": "I find social interactions draining and tiring.",
  "73": "I tend to get angry easily.",
  "74": "I rarely lose my temper.",
  "75": "Small annoyances don't bother me much.",
  "76": "I often feel irritated.",
  "77": "I often feel anxious and nervous.",
  "78": "I am generally calm, even in tense situations.",
  "79": "I worry about things that might go wrong.",
  "80": "I handle stress well.",
  "81": "I often feel downhearted and blue.",
  "82": "I am a generally happy person.",
  "83": "I sometimes feel that life isn't worth living.",
  "84": "I find joy in simple things.",
  "85": "I often act on the spur of the moment without thinking.",
  "86": "I find myself giving in to temptation easily.",
  "87": "I have difficulty resisting cravings.",
  "88": "I sometimes overindulge and regret it later.",
  "89": "I am self-conscious about what others think of me.",
  "90": "I am comfortable being myself in social situations.",
  "91": "I often worry about how I come across to others.",
  "92": "I feel at ease in social situations.",
  "93": "I often feel anxious or nervous about the future.",
  "94": "Criticism or disapproval affects me deeply and emotionally.",
  "95": "I tend to worry a lot about different aspects of my life.",
  "96": "I find it challenging to bounce back quickly after facing a setback or failure.",
  "97": "Enjoys engaging in abstract and theoretical thinking.",
  "98": "Prefers innovative and unconventional approaches to problem-solving.",
  "99": "Appreciates the beauty of intellectual and artistic pursuits.",
  "100": "Finds routine and repetitive tasks uninteresting and seeks out mentally stimulating activities.",
  "101": "I am open to considering unconventional ideas.",
  "102": "I stick to traditional and well-established ideas.",
  "103": "I am always eager to try new and exciting activities.",
  "104": "I often seek out new and challenging experiences.",
  "105": "I am drawn to and appreciate artistic expressions.",
  "106": "Predictability is essential in my daily life.",
  "107": "I don't find much value in artistic pursuits.",
  "108": "Exploring different art forms is enjoyable for me.",
  "109": "I enjoy exploring and experiencing new emotions.",
  "110": "I prefer not to delve too deeply into my emotions.",
  "111": "I prefer to keep my emotions private.",
  "112": "I am in touch with a wide range of emotions.",
  "113": "I often daydream and have a vivid imagination.",
  "114": "I like to keep things organized and structured.",
  "115": "Routine and familiarity are comforting to me.",
  "116": "I often find myself lost in creative thoughts.",
  "117": "I enjoy challenging the traditional way of thinking and doing things.",
  "118": "I am often drawn to unconventional or avant-garde forms of art.",
  "119": "I feel comfortable questioning authority and societal norms.",
  "120": "I prefer sticking to established methods and routines."
}


reversal = [2, 4, 6, 8, 9, 12, 14, 16, 19, 20, 22, 24, 29, 30, 31, 32, 36, 41, 44, 45,
            46, 47, 48, 50, 52, 54, 56, 58, 60, 62, 64, 68, 70, 72, 74, 75, 78, 80, 82,
            84, 85, 86, 87, 88, 90, 92, 96, 102, 106, 107, 110, 111, 114, 115, 120]

facets_questions = {
  "Agreeableness": {
    "Altruism": [1, 2, 3, 4],
    "Cooperation": [5, 6, 7, 8],
    "Modesty": [9, 10, 11, 12],
    "Morality": [13, 14, 15, 16],
    "Sympathy": [17, 18, 19, 20],
    "Trust": [21, 22, 23, 24]
  },
  "Conscientiousness": {
    "Achievement Striving": [25, 26, 27, 28],
    "Cautiousness": [29, 30, 31, 32],
    "Self-Efficacy": [33, 34, 35, 36],
    "Dutifulness": [37, 38, 39, 40],
    "Orderliness": [41, 42, 43, 44],
    "Self-Discipline": [45, 46, 47, 48]
  },
  "Extraversion": {
    "Activity Level": [49, 50, 51, 52],
    "Assertiveness": [53, 54, 55, 56],
    "Cheerfulness": [57, 58, 59, 60],
    "Excitement-Seeking": [61, 62, 63, 64],
    "Friendliness": [65, 66, 67, 68],
    "Gregariousness": [69, 70, 71, 72]
  },
  "Neuroticism": {
    "Anger": [73, 74, 75, 76],
    "Anxiety": [77, 78, 79, 80],
    "Depression": [81, 82, 83, 84],
    "Immoderation": [85, 86, 87, 88],
    "Self-Consciousness": [89, 90, 91, 92],
    "Vulnerability": [93, 94, 95, 96]
  },
  "Openness to Experience": {
    "Intellect": [97, 98, 99, 100],
    "Adventurousness": [101, 102, 103, 104],
    "Artistic Interests": [105, 106, 107, 108],
    "Emotionality": [109, 110, 111, 112],
    "Imagination": [113, 114, 115, 116],
    "Liberalism": [117, 118, 119, 120]
  }
}
